version: '2'

services:
  krill:
    image: nlnetlabs/krill:v0.5.0
    restart: always
    networks:
      - krill_internal
      - web
    volumes:
      - krill_data:/var/krill/data/
    environment:
      - KRILL_LOG_LEVEL=debug
      - KRILL_FQDN=${KRILL_FQDN}
      - KRILL_AUTH_TOKEN=${KRILL_AUTH_TOKEN}
      - KRILL_CLI_TOKEN=${KRILL_AUTH_TOKEN}
      - TZ=Europe/Amsterdam \
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.krill-http.redirectscheme.scheme=https"
      - "traefik.http.routers.krill-http.entrypoints=web"
      - "traefik.http.routers.krill-http.rule=Host(`${KRILL_FQDN}`)"
      - "traefik.http.routers.krill-http.middlewares=krill-https@docker"
      - "traefik.http.routers.krill-https.entrypoints=web-secure"
      - "traefik.http.routers.krill-https.rule=Host(`${KRILL_FQDN}`)"
      - "traefik.http.routers.krill-https.tls=true"
      - "traefik.http.routers.krill-https.tls.certresolver=default"
      - "traefik.http.services.krill.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.krill-http.headers.customresponseheaders.X-Instance=krill"
      - "traefik.http.middlewares.krill-https.headers.customresponseheaders.X-Instance=krill"
  krill_publish:
    image: nlnetlabs/krill:v0.5.0
    restart: always
    networks:
      - krill_internal
      - web
    volumes:
      - ./krill_publish/krill.conf:/var/krill/data/krill.conf:ro
      - krill_publish_data:/data/
      - krill_publish_rsync:/data/repo/rsync/
    environment:
      - KRILL_LOG_LEVEL=debug
      - KRILL_FQDN=${KRILL_PUBLISH_FQDN}
      - KRILL_AUTH_TOKEN=${KRILL_AUTH_TOKEN}
      - KRILL_CLI_TOKEN=${KRILL_AUTH_TOKEN}
      - TZ=Europe/Amsterdam \
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.krillpublish-http.redirectscheme.scheme=https"
      # Two differing service names because otherwise requests for both
      # virtualhosts are loadbalanced between the two containers with differing
      # configs.
      - "traefik.http.routers.krillpublish-http.entrypoints=web"
      - "traefik.http.routers.krillpublish-http.rule=Host(`${KRILL_PUBLISH_FQDN}`)"
      - "traefik.http.routers.krillpublish-http.middlewares=krillpublish-https@docker"
      - "traefik.http.routers.krillpublish-https.entrypoints=web-secure"
      - "traefik.http.routers.krillpublish-https.rule=(Host(`${KRILL_PUBLISH_FQDN}`) && (Path(`/rrdp{postfix:.*}`) || Path(`/repo{postfix:.*}`) || Path(`/rfc8181{postfix:.*}`)))"
      - "traefik.http.routers.krillpublish-https.tls=true"
      - "traefik.http.routers.krillpublish-https.tls.certresolver=default"
      - "traefik.http.services.krillpublish.loadbalancer.server.scheme=https"
      - "traefik.http.middlewares.krillpublish-http.headers.customresponseheaders.X-Instance=krillpublish"
      - "traefik.http.middlewares.krillpublish-https.headers.customresponseheaders.X-Instance=krillpublish"
  rsyncd:
    image: vimagick/rsyncd
    ports:
      - "873:873"
    volumes:
      - ./rsyncd/rsyncd.conf:/etc/rsyncd.conf
      - krill_publish_rsync:/repo
    restart: always
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command:
      - --api.insecure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/usersfile:/usersfile
      - ./traefik:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`${TRAEFIK_API_FQDN}`)"
    #   - "traefik.http.routers.api.service=api@internal"
    #   - "traefik.http.routers.api.middlewares=auth"
    #   - "traefik.http.middlewares.auth.digestauth.realm=monitoring"
    #   - "traefik.http.middlewares.auth.digestauth.usersfile=/usersfile"
    #   - "traefik.http.routers.api.tls=true"
    #   - "traefik.http.routers.api.tls.certresolver=default"

volumes:
  krill_data:
    driver: local
  krill_publish_data:
    driver: local
  krill_publish_rsync:
    driver: local

networks:
  krill_internal:
    driver: bridge
  web:
    external: true

