version: '2'

services:
  krill:
    image: nlnetlabs/krill:v0.5.0
    restart: always
    networks:
      - krill_internal
      - web
    expose:
      - 3000
    volumes:
      - krill_data:/var/krill/data/
    environment:
      - KRILL_LOG_LEVEL=debug
      - KRILL_FQDN=${KRILL_FQDN}
      - KRILL_AUTH_TOKEN=${KRILL_AUTH_TOKEN}
      - KRILL_CLI_TOKEN=${KRILL_AUTH_TOKEN}
      - TZ=Europe/Amsterdam \
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.krill-https.redirectscheme.scheme=https"
      - "traefik.http.routers.krill-http.entrypoints=web"
      - "traefik.http.routers.krill-http.rule=Host(`${KRILL_FQDN}`)"
      - "traefik.http.routers.krill-http.middlewares=krill-https@docker"
      - "traefik.http.routers.krill.entrypoints=web-secure"
      - "traefik.http.routers.krill.rule=Host(`${KRILL_FQDN}`)"
      - "traefik.http.routers.krill.tls=true"
      - "traefik.http.routers.krill.tls.certresolver=default"
      - "traefik.http.services.service0.loadbalancer.server.scheme=https"
  krill_publish:
    image: nlnetlabs/krill:v0.5.0
    restart: always
    expose:
      - 3000
    networks:
      - krill_internal
      - web
    volumes:
      - ./krill_publish/krill.conf:/var/krill/data/krill.conf:ro
      - krill_publish_data:/data/
      - krill_publish_rsync:/data/repo/rsync/
    environment:
      - KRILL_LOG_LEVEL=debug
      - KRILL_FQDN=${KRILL_PUBLISH_FQDN}
      - KRILL_AUTH_TOKEN=${KRILL_AUTH_TOKEN}
      - KRILL_CLI_TOKEN=${KRILL_AUTH_TOKEN}
      - TZ=Europe/Amsterdam \
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.krill-publish-https.redirectscheme.scheme=https"
      - "traefik.http.routers.krill-publish-http.entrypoints=web"
      - "traefik.http.routers.krill-publish-http.rule=Host(`${KRILL_PUBLISH_FQDN}`)"
      - "traefik.http.routers.krill-publish-http.middlewares=krill-publish-https@docker"
      - "traefik.http.routers.krill-publish.entrypoints=web-secure"
      - "traefik.http.routers.krill-publish.rule=Host(`${KRILL_PUBLISH_FQDN}`)"
      - "traefik.http.routers.krill-publish.tls=true"
      - "traefik.http.routers.krill-publish.tls.certresolver=default"
      - "traefik.http.services.service0.loadbalancer.server.scheme=https"
  rsyncd:
    image: vimagick/rsyncd
    ports:
      - "873:873"
    volumes:
      - ./rsyncd/rsyncd.conf:/etc/rsyncd.conf
      - krill_publish_rsync:/repo
    restart: always
  traefik:
    container_name: traefik
    image: traefik
    restart: unless-stopped
    command:
      - --api.insecure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/usersfile:/usersfile
      - ./traefik:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.api.rule=Host(`${TRAEFIK_API_FQDN}`)"
    #   - "traefik.http.routers.api.service=api@internal"
    #   - "traefik.http.routers.api.middlewares=auth"
    #   - "traefik.http.middlewares.auth.digestauth.realm=monitoring"
    #   - "traefik.http.middlewares.auth.digestauth.usersfile=/usersfile"
    #   - "traefik.http.routers.api.tls=true"
    #   - "traefik.http.routers.api.tls.certresolver=default"

volumes:
  krill_data:
    driver: local
  krill_publish_data:
    driver: local
  krill_publish_rsync:
    driver: local

networks:
  krill_internal:
    driver: bridge
  web:
    external: true

